[package]
name = "hoverlay"
version = "0.1.0"
edition = "2024"

[dependencies]
cosmic-text = "0.19.0"
ctrlc = { version = "3.5.2", features = ["termination"] }
etcetera = "0.11.0"
mlua = { version = "0.12.1", features = ["lua55", "vendored"] }
softbuffer = "0.4.8"
sys-locale = "0.3.2"
unicode-script = "0.5.8"
winit = "0.30.13"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
debug = false
incremental = false
